### ISSUE TITLE
sqllite  断线导致程序退出

### ISSUE THREAD

**Issue by yushuiying** [openim-sigs/oimws#109]
我们的测试流程是这样的：
1、用google chrome浏览器手机模式正常登录一个聊天用户开始聊天
2、用相同的浏览器开另外一个无痕窗口，登录同一个用户
这时必定会报下图中的错误，从而导致程序退出

![微信图片_20240227114402](https://github.com/openim-sigs/oimws/assets/28528274/e163c17c-982c-42ea-b368-51bb35abdd7f)
![微信图片_20240227134347](https://github.com/openim-sigs/oimws/assets/28528274/40418ae9-b7fb-4cdc-9109-bc843351de7c)

**Comment by FGadvancer** [comment]
related to the issue #93
